config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  namespace :admin do
    resources :statistics, only: [:index]
  end

  get 'admin/index'
  root 'pages#index'
  resources :online_reservations, only: [:new, :create, :show]
  get 'search_ticket', to: 'online_reservations#search', as: "search_ticket"

  authenticated :admin_user do
    root to: 'admin#index', as: :root_admin
  end
  
  get 'admin' => 'admin#index'




  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up              that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/online_reservation.rb
class OnlineReservation < ApplicationRecord
  has_many :tickets
  enum status: { pending: 'pending', confirmed: 'confirmed', canceled: 'canceled' }
  after_create :set_status_pending
  
  private

  def set_status_pending
    self.update(status: :pending)
  end
end

app/controllers/admin/statistics_controller.rb
class Admin::StatisticsController < AdminController
  def index
    @online_reservations = OnlineReservation.all.group_by(&:date).map { |date, reservations| [date, reservations.count] }
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @online_reservations = OnlineReservation.all
    @pending_count = @online_reservations.where(status: "pending").count
    @confirmed_count = @online_reservations.where(status: "confirmed").count
    @canceled_count = @online_reservations.where(status: "canceled").count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/online_reservations_controller.rb
# app/controllers/online_reservations_controller.rb
class OnlineReservationsController < ApplicationController
  before_action :set_online_reservation, only: [:show]

  def search
    if params[:ticket_id].present?
      @ticket_id = params[:ticket_id]

      if OnlineReservation.find(@ticket_id).present?
        redirect_to online_reservation_path(@ticket_id)
        return # Ensure to exit the action after redirection
      else
        flash[:alert] = "Ticket not found"
      end
    else
      flash[:alert] = "Please enter a ticket ID"
    end
  end

  def new
    @online_reservation = OnlineReservation.new
  end

  def create
    @online_reservation = OnlineReservation.new(online_reservation_params)
    if @online_reservation.save
      redirect_to online_reservation_path(@online_reservation), notice: 'Online reservation was successfully created.'
    else
      flash[:alert] = 'Failed to create online reservation.'
      redirect_to root_path
    end
  end

  def show
    # unless request.referrer && URI(request.referrer).path == search_ticket_path
    #   flash[:alert] = "Access denied."
    #   redirect_to search_ticket_path
    # end
  end

  private

  def set_online_reservation
    @online_reservation = OnlineReservation.find(params[:id])
  end

  def online_reservation_params
    params.require(:online_reservation).permit(:name, :phone_number, :pax, :date, :time, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/admin/statistics_helper.rb
module Admin::StatisticsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/_reservations_tbl.html.erb
<table id="customers">
  <thead>
    <th>Ticket ID</th>
    <th>Name</th>
    <th>Phone Number</th>
    <th>Pax</th>
    <th>Date</th>
    <th>Time</th>
    <th>Message</th>
    <th>status</th>
  </thead>
  <tbody>
    <% @online_reservations.each do |ticket| %>
      <tr>
        <td><%= ticket.id %></td>
        <td><%= ticket.name %></td>
        <td><%= ticket.phone_number %></td>
        <td><%= ticket.pax %></td>
        <td><%= ticket.date.strftime("%m/%d/%Y") %></td>
        <td><%= ticket.time.strftime("%I:%M%p")  %></td>
        <td><%= ticket.message %></td>
        <td><%= ticket.status %></td>
      <tr>
    <% end %>
  </tbody>
</table>

app/views/admin/index.html.erb
<div class="customer--status">
  <div class="card">
    <h2>Pending</h2>
    <h1><%= @pending_count %></h1>
  </div>

  <div class="card">
    <h2>Process</h2>
    <h1><%= @confirmed_count %></h1>
  </div>

  <div class="card">
    <h2>Cancel</h2>
    <h1><%= @canceled_count %></h1>
  </div>
</div>
<%= render 'reservations_tbl' %>

app/views/admin/statistics/index.html.erb
<div data-controller="statistics" 
    data-dashboard-revenue-value="<%= @online_reservations.to_json %>" >
  <%= form_tag online_reservations_path, method: :get do %>
    <%= label_tag :start_date, "Start Date" %>
    <%= date_field_tag :start_date, @start_date %>

    <%= label_tag :end_date, "End Date" %>
    <%= date_field_tag :end_date, @end_date %>

    <%= submit_tag "Filter" %>
  <% end %>
  <canvas id="line-chart" ></canvas>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer section has-bg-image text-center"
  style="background-image: url('<%= asset_path('footer-bg.jpg') %>')">
  <div class="container">

    <div class="footer-top grid-list">

      <div class="footer-brand has-before has-after">

        <a href="#" class="logo">
          <%= image_tag('logo.svg', width: 160, height: 50, loading: 'lazy', alt: 'grilli home') %>
        </a>

        <address class="body-4">
          Restaurant St, Delicious City, London 9578, UK
        </address>

        <a href="mailto:booking@grilli.com" class="body-4 contact-link">booking@grilli.com</a>

        <a href="tel:+88123123456" class="body-4 contact-link">Booking Request : +88-123-123456</a>

        <p class="body-4">
          Open : 09:00 am - 01:00 pm
        </p>

        <div class="wrapper">
          <div class="separator"></div>
          <div class="separator"></div>
          <div class="separator"></div>
        </div>

        <p class="title-1">Get News & Offers</p>

        <p class="label-1">
          Subscribe us & Get <span class="span">25% Off.</span>
        </p>

        <%= form_with(url: '/subscribe', method: 'post', class: 'input-wrapper') do |f| %>
          <div class="icon-wrapper">
            <ion-icon name="mail-outline" aria-hidden="true"></ion-icon>

            <%= f.email_field :email_address, placeholder: 'Your email', class: 'input-field' %>
          </div>

          <button type="submit" class="btn btn-secondary">
            <span class="text text-1">Subscribe</span>

            <span class="text text-2" aria-hidden="true">Subscribe</span>
          </button>
        <% end %>

      </div>

      <ul class="footer-list">
        <li>

          <%= link_to '#Home', class: 'label-2 footer-link hover-underline' do %>
            Home
          <% end %>
        </li>
        <li>
          <%= link_to '#Menus', class: 'label-2 footer-link hover-underline' do %>
            Menus
          <% end %>
        </li>
        <li>
          <%= link_to '#About Us', class: 'label-2 footer-link hover-underline' do %>
            About
          <% end %>
        </li>
        <li>
          <%= link_to '#Our Chefs', class: 'label-2 footer-link hover-underline' do %>
            Out Chefs
          <% end %>
        </li>
        <li>
          <%= link_to '#Contact', class: 'label-2 footer-link hover-underline' do %>
            Contact
          <% end %>
        </li>
      </ul>

      <ul class="footer-list">
        <li>
          <%= link_to 'Facebook', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
        <li>
          <%= link_to 'Instagram', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
        <li>
          <%= link_to 'Twitter', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
        <li>
          <%= link_to 'Youtube', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
        <li>
          <%= link_to 'Google Map', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
      </ul>

    </div>

    <div class="footer-bottom">
      <p class="copyright">
        &copy; <%= Time.now.year %> Grilli. All Rights Reserved | Crafted by <%= link_to 'codewithsadee', 'https://github.com/codewithsadee', target: '_blank', class: 'link' %>
      </p>
    </div>

  </div>
</footer>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grilli</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  </head>

  <body>
    <div class="admin-container">
      <div class="admin-sidebar ">
        <a href="#" class="logo">
          <%= image_tag("logo.svg", width: 160, height: 50, alt: "Grilli - Home") %>
        </a>

        <ul>
          <li><%= link_to "Dashboard", admin_path %></li>
          <li><%= link_to "Statistics", admin_statistics_path %></li>
          <% if admin_signed_in? %>
            <li>
              <%= link_to destroy_admin_session_path, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to sign out?" }, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                  sign out
                <% end %>
            </li>
          <% end %>
          
          
        </ul>
      </div>
      <div class="admin-content">
        <%= yield %>
      </div>
    </div >
    
        
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grilli</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/online_reservations/search.html.erb
<div class="topbar">
  <div class="container">

    <address class="topbar-item">
      <div class="icon">
        <ion-icon name="location-outline" aria-hidden="true"></ion-icon>
      </div>

      <span class="span">
        Restaurant St, Delicious City, London 9578, UK
      </span>
    </address>

    <div class="separator"></div>

    <div class="topbar-item item-2">
      <div class="icon">
        <ion-icon name="time-outline" aria-hidden="true"></ion-icon>
      </div>

      <span class="span">Daily : 8.00 am to 10.00 pm</span>
    </div>

    <a href="tel:+11234567890" class="topbar-item link">
      <div class="icon">
        <ion-icon name="call-outline" aria-hidden="true"></ion-icon>
      </div>

      <span class="span">+1 123 456 7890</span>
    </a>

    <div class="separator"></div>

    <a href="mailto:booking@restaurant.com" class="topbar-item link">
      <div class="icon">
        <ion-icon name="mail-outline" aria-hidden="true"></ion-icon>
      </div>

      <span class="span">booking@restaurant.com</span>
    </a>

  </div>
</div>


<header class="header " data-controller="header"  data-header-target="header">
  <div class="container">
    <a href="#" class="logo">
      <%= image_tag("logo.svg", width: 160, height: 50, alt: "Grilli - Home") %>
    </a>
  </div>
</header>

<div class="footer section has-bg-image text-center"
  style="background-image: url('<%= asset_path('footer-bg.jpg') %>')">
  <div class="container">

    <div class="footer-top grid-list">

      <div class="footer-brand has-before has-after">
        <p class="title-1">Ticket Search</p>
        
        <div class="wrapper">
          <div class="separator"></div>
          <div class="separator"></div>
          <div class="separator"></div>
        </div>

        <%= form_tag(search_ticket_path, method: "get", class: 'input-wrapper') do %>
          <div class="icon-wrappe">

            <%= text_field_tag(:ticket_id, nil, class: "input-field", placeholder: "Enter Ticket ID") %>

          </div>
          <%= submit_tag("Search", class: "btn btn-secondary") %>
        <% end %>
      </div>

      <ul class="footer-list">
        <li>
          <%= link_to 'Back', root_path, class: 'label-2 footer-link hover-underline' %>
        </li>
      </ul>

      <ul class="footer-list">
        <li>
          <%= link_to 'Facebook', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
        <li>
          <%= link_to 'Instagram', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
        <li>
          <%= link_to 'Twitter', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
        <li>
          <%= link_to 'Youtube', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
        <li>
          <%= link_to 'Google Map', '#', class: 'label-2 footer-link hover-underline' %>
        </li>
      </ul>

    </div>

    <div class="footer-bottom">
      <p class="copyright">
        &copy; <%= Time.now.year %> Grilli. All Rights Reserved | Crafted by <%= link_to 'codewithsadee', 'https://github.com/codewithsadee', target: '_blank', class: 'link' %>
      </p>
    </div>

  </div>
</div>

app/views/online_reservations/show.html.erb
<footer class="footer section has-bg-image text-center" style="background-image: url('<%= asset_path('footer-bg.jpg') %>')">
  <div class="container">
    <div class="footer-top grid-list">
      <div class="footer-brand has-before has-after">
        <a href="#" class="logo">
          <%= image_tag('logo.svg', width: 160, height: 50, loading: 'lazy', alt: 'grilli home') %>
        </a>
        <address class="body-4">
          Restaurant St, Delicious City, London 9578, UK
        </address>
        <a href="mailto:booking@grilli.com" class="body-4 contact-link">booking@grilli.com</a>
        <a href="tel:+88123123456" class="body-4 contact-link">Booking Request : +88-123-123456</a>
        <p class="body-4">
          Open : 09:00 am - 01:00 pm
        </p>
        <div class="wrapper">
          <div class="separator"></div>
          <div class="separator"></div>
          <div class="separator"></div>
        </div>
        <p class="title-1">Ticket Reservation</p>
        <p class="label-1">
          Name: <%=@online_reservation.name %><br>
          Phone Number: <%=@online_reservation.phone_number %><br>
          Pax: <%=@online_reservation.pax %><br>
          Date: <%=@online_reservation.date.strftime("%B %d, %Y") %><br>
          Time: <%=@online_reservation.time.strftime("%I:%M %p") %><br>
          Message: <%=@online_reservation.message %>
        </p>
      </div>
      <ul class="footer-list">
        <li>
          <%= link_to root_path, class: 'label-2 footer-link hover-underline' do %>
            Home
          <% end %>
        </li>
        <!-- Other list items -->
      </ul>
      <ul class="footer-list">
        <!-- Other list items -->
      </ul>
    </div>
    <div class="footer-bottom">
      <p class="copyright">
        &copy; <%= Time.now.year %> Grilli. All Rights Reserved | Crafted by <%= link_to 'codewithsadee', 'https://github.com/codewithsadee', target: '_blank', class: 'link' %>
      </p>
    </div>
  </div>
</footer>

app/views/pages/index.html.erb
<%= render "shared/topbar" %>
<%= render "shared/header" %>
<main>
  <article>
    <%= render "shared/hero" %>
    <%= render "shared/service" %>
    <%= render "shared/about" %>
    <%= render "shared/special_dish" %>
    <%= render "shared/menu" %>
    <%= render "shared/testimonial" %>
    <%= render "shared/reservation" %>
    <%= render "shared/feature" %>
    <%= render "shared/event" %>
  </article>
</main>
<%= render "layouts/footer" %>









  <!-- 
    - #BACK TO TOP
  -->

  <a href="#top" class="back-top-btn active" aria-label="back to top" data-back-top-btn>
    <ion-icon name="chevron-up" aria-hidden="true"></ion-icon>
  </a>

app/views/shared/_about.html.erb
<section class="section about text-center" aria-labelledby="about-label" id="about">
  <div class="container">

    <div class="about-content">

      <p class="label-2 section-subtitle" id="about-label">Our Story</p>

      <h2 class="headline-1 section-title">Every Flavor Tells a Story</h2>

      <p class="section-text">
        Lorem Ipsum is simply dummy text of the printingand typesetting industry lorem Ipsum has been the
        industrys standard dummy text ever since the when an unknown printer took a galley of type and scrambled
        it to make a type specimen book It has survived not only five centuries, but also the leap into.
      </p>

      <div class="contact-label">Book Through Call</div>

      <a href="tel:+804001234567" class="body-1 contact-number hover-underline">+80 (400) 123 4567</a>

      <%= link_to "#", class: "btn btn-primary" do %>
        <span class="text text-1">Read More</span>
        <span class="text text-2" aria-hidden="true">Read More</span>
      <% end %>

    </div>

    <figure class="about-banner">

      <%= image_tag("about-banner.jpg", width: 570, height: 570, loading: "lazy", alt: "about banner", class: "w-100", data: { parallax_item: true, parallax_speed: 1 }) %>

      <div class="abs-img abs-img-1 has-before" data-parallax-item data-parallax-speed="1.75">
        <%= image_tag("about-abs-image.jpg", width: 285, height: 285, loading: "lazy", alt: "", class: "w-100") %>
      </div>

      <div class="abs-img abs-img-2 has-before">
        <%= image_tag("badge-2.png", width: 133, height: 134, loading: "lazy", alt: "") %>
      </div>

    </figure>

    <%= image_tag("shape-3.png", width: 197, height: 194, loading: "lazy", alt: "", class: "shape") %>

  </div>
</section>

app/views/shared/_event.html.erb
<section class="section event bg-black-10" aria-label="event" id="blogs">
  <div class="container">
    <p class="section-subtitle label-2 text-center">Recent Updates</p>
    <h2 class="section-title headline-1 text-center">Upcoming Event</h2>
    <ul class="grid-list">
      <li>
        <div class="event-card has-before hover:shine">
          <div class="card-banner img-holder" style="--width: 350; --height: 450;">
            <%= image_tag('event-1.jpg', width: 350, height: 450, loading: 'lazy', alt: 'Flavour so good you’ll try to eat with your eyes.', class: 'img-cover') %>
            <time class="publish-date label-2" datetime="2022-09-15">15/09/2022</time>
          </div>
          <div class="card-content">
            <p class="card-subtitle label-2 text-center">Food, Flavour</p>
            <h3 class="card-title title-2 text-center">
              Flavour so good you’ll try to eat with your eyes.
            </h3>
          </div>
        </div>
      </li>
      <li>
        <div class="event-card has-before hover:shine">
          <div class="card-banner img-holder" style="--width: 350; --height: 450;">
            <%= image_tag('event-2.jpg', width: 350, height: 450, loading: 'lazy', alt: 'Flavour so good you’ll try to eat with your eyes.', class: 'img-cover') %>
            <time class="publish-date label-2" datetime="2022-09-08">08/09/2022</time>
          </div>
          <div class="card-content">
            <p class="card-subtitle label-2 text-center">Healthy Food</p>
            <h3 class="card-title title-2 text-center">
              Flavour so good you’ll try to eat with your eyes.
            </h3>
          </div>
        </div>
      </li>
      <li>
        <div class="event-card has-before hover:shine">
          <div class="card-banner img-holder" style="--width: 350; --height: 450;">
            <%= image_tag('event-3.jpg', width: 350, height: 450, loading: 'lazy', alt: 'Flavour so good you’ll try to eat with your eyes.', class: 'img-cover') %>
            <time class="publish-date label-2" datetime="2022-09-03">03/09/2022</time>
          </div>
          <div class="card-content">
            <p class="card-subtitle label-2 text-center">Recipe</p>
            <h3 class="card-title title-2 text-center">
              Flavour so good you’ll try to eat with your eyes.
            </h3>
          </div>
        </div>
      </li>
    </ul>
    <%= link_to 'View Our Blog', '#', class: 'btn btn-primary' %>
  </div>
</section>

app/views/shared/_feature.html.erb
<section class="section features text-center" aria-label="features">
  <div class="container">
    <p class="section-subtitle label-2">Why Choose Us</p>
    <h2 class="headline-1 section-title">Our Strength</h2>
    <ul class="grid-list">
      <li class="feature-item">
        <div class="feature-card">
          <div class="card-icon">
            <%= image_tag('features-icon-1.png', width: 100, height: 80, loading: 'lazy', alt: 'icon') %>
          </div>
          <h3 class="title-2 card-title">Hygienic Food</h3>
          <p class="label-1 card-text">Lorem Ipsum is simply dummy printing and typesetting.</p>
        </div>
      </li>
      <li class="feature-item">
        <div class="feature-card">
          <div class="card-icon">
            <%= image_tag('features-icon-2.png', width: 100, height: 80, loading: 'lazy', alt: 'icon') %>
          </div>
          <h3 class="title-2 card-title">Fresh Environment</h3>
          <p class="label-1 card-text">Lorem Ipsum is simply dummy printing and typesetting.</p>
        </div>
      </li>
      <li class="feature-item">
        <div class="feature-card">
          <div class="card-icon">
            <%= image_tag('features-icon-3.png', width: 100, height: 80, loading: 'lazy', alt: 'icon') %>
          </div>
          <h3 class="title-2 card-title">Skilled Chefs</h3>
          <p class="label-1 card-text">Lorem Ipsum is simply dummy printing and typesetting.</p>
        </div>
      </li>
      <li class="feature-item">
        <div class="feature-card">
          <div class="card-icon">
            <%= image_tag('features-icon-4.png', width: 100, height: 80, loading: 'lazy', alt: 'icon') %>
          </div>
          <h3 class="title-2 card-title">Event & Party</h3>
          <p class="label-1 card-text">Lorem Ipsum is simply dummy printing and typesetting.</p>
        </div>
      </li>
    </ul>
    <%= image_tag('shape-7.png', width: 208, height: 178, loading: 'lazy', alt: 'shape', class: 'shape shape-1') %>
    <%= image_tag('shape-8.png', width: 120, height: 115, loading: 'lazy', alt: 'shape', class: 'shape shape-2') %>
  </div>
</section>

app/views/shared/_header.html.erb
<header class="header " data-controller="header"  data-header-target="header" data-controller="navbar">
  <div class="container">
    <a href="#" class="logo">
      <%= image_tag("logo.svg", width: 160, height: 50, alt: "Grilli - Home") %>
    </a>

    <nav class="navbar">

      <button class="close-btn" aria-label="close menu" data-nav-toggler>
        <ion-icon name="close-outline" aria-hidden="true"></ion-icon>
      </button>

      <a href="#" class="logo">
        <img src="./assets/images/logo.svg" width="160" height="50" alt="Grilli - Home">
      </a>

      <ul class="navbar-list">

        <li class="navbar-item">
          <a href="#home" class="navbar-link hover-underline active">
            <div class="separator"></div>
            <span class="span">Home</span>
          </a>
        </li>

        <li class="navbar-item">
          <a href="#menu" class="navbar-link hover-underline">
            <div class="separator"></div>

            <span class="span">Menus</span>
          </a>
        </li>

        <li class="navbar-item">
          <a href="#about" class="navbar-link hover-underline">
            <div class="separator"></div>

            <span class="span">About Us</span>
          </a>
        </li>

        <li class="navbar-item">
          <a href="#reservation" class="navbar-link hover-underline">
            <div class="separator"></div>

            <span class="span">Online Reservation</span>
          </a>
        </li>

        <li class="navbar-item">
          <a href="#blogs" class="navbar-link hover-underline">
            <div class="separator"></div>

            <span class="span">Blogs</span>
          </a>
        </li>

      </ul>

      <div class="text-center">
        <p class="headline-1 navbar-title">Visit Us</p>

        <address class="body-4">
          Restaurant St, Delicious City, <br>
          London 9578, UK
        </address>

        <p class="body-4 navbar-text">Open: 9.30 am - 2.30pm</p>

        <a href="mailto:booking@grilli.com" class="body-4 sidebar-link">booking@grilli.com</a>

        <div class="separator"></div>

        <p class="contact-label">Booking Request</p>

        <a href="tel:+88123123456" class="body-1 contact-number hover-underline">
          +88-123-123456
        </a>
      </div>

    </nav>

    <a  href="#reservation" class="btn btn-secondary">
      <span class="text text-1">Find A Table</span>

      <span class="text text-2" aria-hidden="true">Find A Table</span>
    </a>

    <button class="nav-open-btn" aria-label="open menu" data-nav-toggler>
      <span class="line line-1"></span>
      <span class="line line-2"></span>
      <span class="line line-3"></span>
    </button>

    <div class="overlay" data-nav-toggler data-overlay></div>

  </div>
</header>

app/views/shared/_preloader.html.erb
<div class="preload" data-preaload>
  <div class="circle"></div>
  <p class="text">Grilli</p>
</div>

app/views/shared/_special_dish.html.erb
<section class="special-dish text-center" aria-labelledby="dish-label">

  <div class="special-dish-banner">
    <%= image_tag("special-dish-banner.jpg", width: 940, height: 900, loading: "lazy", alt: "special dish", class: "img-cover") %>
  </div>

  <div class="special-dish-content bg-black-10">
    <div class="container">

      <%= image_tag("badge-1.png", width: 28, height: 41, loading: "lazy", alt: "badge", class: "abs-img") %>

      <p class="section-subtitle label-2">Special Dish</p>

      <h2 class="headline-1 section-title">Lobster Tortellini</h2>

      <p class="section-text">
        Lorem Ipsum is simply dummy text of the printingand typesetting industry lorem Ipsum has been the
        industrys standard dummy text ever since the when an unknown printer took a galley of type.
      </p>

      <div class="wrapper">
        <del class="del body-3">$40.00</del>

        <span class="span body-1">$20.00</span>
      </div>

      <%= link_to "#", class: "btn btn-primary" do %>
        <span class="text text-1">View All Menu</span>
        <span class="text text-2" aria-hidden="true">View All Menu</span>
      <% end %>

    </div>
  </div>

  <%= image_tag("shape-4.png", width: 179, height: 359, loading: "lazy", alt: "", class: "shape shape-1") %>

  <%= image_tag("shape-9.png", width: 351, height: 462, loading: "lazy", alt: "", class: "shape shape-2") %>

</section>

app/views/shared/_testimonial.html.erb
<section class="section testi text-center has-bg-image"
        style="background-image: url('<%= asset_path('testimonial-bg.jpg') %>')" aria-label="testimonials">
  <div class="container">
    <div class="quote">”</div>
    <p class="headline-2 testi-text">
      I wanted to thank you for inviting me down for that amazing dinner the other night. The food was extraordinary.
    </p>
    <div class="wrapper">
      <div class="separator"></div>
      <div class="separator"></div>
      <div class="separator"></div>
    </div>
    <div class="profile">
      <%= image_tag('testi-avatar.jpg', width: 100, height: 100, loading: 'lazy', alt: 'Sam Jhonson', class: 'img') %>
      <p class="label-2 profile-name">Sam Jhonson</p>
    </div>
  </div>
</section>